#!/bin/sh
if [ "$1" = "remove" ]; then
  if [ -x "`which gtk-update-icon-cache 2>/dev/null`" ]; then
    gtk-update-icon-cache -f /usr/share/icons/hicolor
  fi

  if [ -x "`which update-mime-database 2>/dev/null`" ]; then
    update-mime-database /usr/share/mime
  fi

  if [ -x "`which update-desktop-database 2>/dev/null`" ]; then
    update-desktop-database -q
  fi
fi
